server:
  port: 5000
spring:
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
#각각의 변수에 값이 들어가야 하는데 데이터베이스는 EB가 만들어주므로 EB가 어플리케이션을 실행하면서 값을 지정해줄 수 있음
#MYSQL을 사용함
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${rds.username}
    password: ${rds.password}