spring: #스프링부트 설정을 위한 최상위 키워드
  security: #스프링 시큐리티 설정
    oauth2: #Oauth2 인증관련 설정
      client: #Oauth2 클라이언트(여기서는 나 자신) 설정
        registration: #Oauth2 클라이언트 등록설정
          github: #GitHub Oauth2 클라이언트 설정(이름을 github로 정의함, 구글이면 구글, 페북이면 페북)
            clientId: Ov23lipb4PP7girWaybV #client의 Oauth2앱의 클라이언트 Id (GitHub에서 발급받은 값이 들어감)
            clientSecret: 779269f316dd2feb9d966bb2d7aa6e502b6a6fd1 #GitHub Oauth2앱의 클라이언트 시크릿
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}" #Oauth2 인증 후 리다이렉션이 되는 URL, {baseUrl}은 애플리케이션의 기본 URL, 클라이언트 등록 ID(여기서는 'GitHub')
            scope: #GitHub API를 사용할 대 요청할 권한의 범위
              - user:email #사용자의 이메일 정보를 요청하는 범위
              - read:user #사용자의 기본프로필 정보를 요청하는 범위
    provider: #Oauth2 제공자 설정
      github: #GitHub Oauth2제공자 관련 설정
        authorization-uri: https://github.com/login/oauth/authorize
		#사용자를 GitHub 로그인 페이지로 리다이렉션하는 URI, GitHub OAuth2 인증의 시작점
  	token-uri: https://github.com/login/oauth/access_token
        user-info-uri: https://api.github.com/use
