spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23lipb4PP7girWaybV
            clientSecret: 779269f316dd2feb9d966bb2d7aa6e502b6a6fd1
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
    provider:
      github:
        authorization-uri: https://github.com/login/oauth/authorize
        token-uri: https://github.com/login/oauth/access_token
        user-info-uri: https://api.github.com/user